### ISSUE TITLE
Character Encoding Issues

### ISSUE THREAD

**Issue by VladPerervenko** [thierrymoudiki/nnetsauce#13] opened 2020-06-10 18:07 UTC
```r
 X <- as.matrix(iris[, 1:4])
 y <- as.integer(iris[, 5]) - 1L
 obj <- sklearn$tree$DecisionTreeClassifier()
 obj2 <- RandomBagClassifier(
     obj,
     n_estimators = 10L,
     n_hidden_features = 1L,
     activation_name = "relu",
     a = 0.01,
     nodes_sim = "sobol",
     bias = TRUE,
     dropout = 0,
     direct_link = FALSE,
     n_clusters = 2L,
     cluster_encode = TRUE,
     type_clust = "kmeans",
     col_sample = 1,
     row_sample = 1,
     n_jobs = NULL,
     seed = 123L,
     verbose = 1L
 )
 obj2$fit(X, y)
```
```bash
 0/10 [..............................] - ETA: 0sОшибка в py_call_impl(callable, dots$args, dots$keywords) :
  UnicodeEncodeError: 'charmap' codec can't encode characters in position 7-9: character maps to <undefined>
Detailed traceback: 
  File "C:\Users\User\AppData\Local\r-miniconda\envs\r-reticulate\lib\site-packages\nnetsauce\randombag\randomBagClassifier.py", line 183, in fit
    pbar.update(m)
  File "C:\Users\User\AppData\Local\r-miniconda\envs\r-reticulate\lib\site-packages\nnetsauce\utils\progress_bar.py", line 117, in update
    sys.stdout.write(bar)
  File "C:/Users/User/AppData/Local/r-miniconda/envs/r-reticulate\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]```

**Comment by thierrymoudiki** [comment] 2020-06-11 10:07
Please, mention that you're using the R version. 
The error always seem to come from `py_call_*` (calls Python from R).

**Comment by VladPerervenko** [comment] 2020-06-11 10:34
`> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=Russian_Russia.1251  LC_CTYPE=Russian_Russia.1251    LC_MONETARY=Russian_Russia.1251
[4] LC_NUMERIC=C                    LC_TIME=Russian_Russia.1251    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] nnetsauce_0.4.0

loaded via a namespace (and not attached):
[1] compiler_3.6.3  Matrix_1.2-18   tools_3.6.3     rappdirs_0.3.1  Rcpp_1.0.4.6    reticulate_1.16
[7] grid_3.6.3      jsonlite_1.6.1  lattice_0.20-41`

**Comment by VladPerervenko** [comment] 2020-06-11 10:43
With the same data (iris), this model runs without problems.
`library(datasets)

X <- as.matrix(iris[, 1:4])
y <- as.integer(iris[, 5]) - 1L

obj <- sklearn$tree$DecisionTreeClassifier()
obj2 <- CustomClassifier(
    obj,
    n_hidden_features = 5L,
    activation_name = "relu",
    a = 0.01,
    nodes_sim = "sobol",
    bias = TRUE,
    dropout = 0,
    direct_link = TRUE,
    n_clusters = 2L,
    cluster_encode = TRUE,
    type_clust = "kmeans",
    col_sample = 1,
    row_sample = 1,
    seed = 123L
)
obj2$fit(X, y)
CustomClassifier(col_sample=1.0, dropout=0.0, obj=DecisionTreeClassifier(),
                 row_sample=1.0)
print(obj2$score(X, y))
[1] 1`

**Comment by thierrymoudiki** [comment] 2020-06-11 12:58
@VladPerervenko Unable to reproduce the error; it works well for me. The best fix that I could suggest right now, is to suppress progress bar printing when you create the object. Try to set: 
```R
verbose = 0L
```

**Comment by VladPerervenko** [comment] 2020-06-11 13:03
Yes, this solves the problem. thank

**Comment by thierrymoudiki** [comment] 2020-06-11 13:04
Cool! Shall we close the issue now?

**Comment by VladPerervenko** [comment] 2020-06-11 13:05
Yes

**Closed** 2020-06-11 13:07 UTC
